---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
#      - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - ./config:/config
      - /path/to/jellyfin/library:/config
      - /path/to/tvseries:/data/tvshows
      - /path/to/movies:/data/movies
      - /path/to/misc:/data/misc
      - /path/to/podcast:/data/podcast
      - /path/to/musicvideo:/data/musicvideo
      - /path/to/doc:/data/doc
    ports:
      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    restart: unless-stopped
    devices:
     - /dev/dri:/dev/dri #for Intel iGPU acceleration

